// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceGuard.Data;

#nullable disable

namespace SpaceGuard.Migrations
{
    [DbContext(typeof(SpaceGuardContext))]
    [Migration("20260608014654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceGuard.Models.AlertaAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SateliteId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SateliteId");

                    b.ToTable("alertas_ambientais", (string)null);
                });

            modelBuilder.Entity("SpaceGuard.Models.IndicadorAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SateliteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SateliteId");

                    b.ToTable("indicadores_ambientais", (string)null);
                });

            modelBuilder.Entity("SpaceGuard.Models.Satelite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("satelites", (string)null);
                });

            modelBuilder.Entity("SpaceGuard.Models.AlertaAmbiental", b =>
                {
                    b.HasOne("SpaceGuard.Models.Satelite", "Satelite")
                        .WithMany("Alertas")
                        .HasForeignKey("SateliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satelite");
                });

            modelBuilder.Entity("SpaceGuard.Models.IndicadorAmbiental", b =>
                {
                    b.HasOne("SpaceGuard.Models.Satelite", "Satelite")
                        .WithMany("Indicadores")
                        .HasForeignKey("SateliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satelite");
                });

            modelBuilder.Entity("SpaceGuard.Models.Satelite", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Indicadores");
                });
#pragma warning restore 612, 618
        }
    }
}
